Repository WildCodeSchool/tours-php-2009-project2-defendthecastle, pull requests merged in 2020-11, with the labels that each got.

#5 Us 18 direct acces
  config/config.php
  public/assets/css/style.css
  public/assets/images/Archer-adverse.png
  public/assets/images/Archer.png
  public/assets/images/Horseman.png
  public/assets/images/knight.png
  public/assets/images/terrain.png
  src/View/Game/troop.html.twig
  src/View/layout.html.twig
Labels: Corrections done

#9 US view attack finished
  public/assets/images/Lancer.png
  public/assets/images/enemyArcher.png
  public/assets/images/enemyHorseman.png
  public/assets/images/enemyLancer.png
  src/Controller/GameController.php
  src/Controller/HomeController.php
  src/Model/EnemyManager.php
  src/Model/Troop.php
  src/View/Game/troop.html.twig
Labels: Corrections done

#20 Us 02 castle name
  README.md
  public/assets/css/style.css
  public/assets/images/castle-30.png
  public/assets/images/castle-40.png
  public/assets/images/castle-50.png
  public/assets/images/favicon.png
  public/assets/images/red-cross.png
  public/assets/images/sword.cur
  src/Controller/AbstractController.php
  src/Controller/GameController.php
  src/Model/AbstractManager.php
  src/Model/Castle.php
  src/Model/CastleManager.php
  src/View/Error/503.html.twig
  src/View/Game/troop.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#7 Adding classes Castle and CastleManager to create castle object with …
  src/Controller/GameController.php
  src/View/Game/troop.html.twig
Labels: Corrections done, Reviewed

#25 Us 07 battle result
  defend_the_castle.sql
  public/assets/css/style.css
  src/Controller/GameController.php
  src/Model/AbstractManager.php
  src/Model/Castle.php
  src/Model/CastleManager.php
  src/Model/EnemyManager.php
  src/Model/SubAbstractManager.php
  src/Model/Troop.php
  src/Model/TroopManager.php
  src/View/Game/troop.html.twig
Labels: Reviewed

#27 Us 14 game rules
  public/assets/css/rules.css
  public/assets/css/style.css
  public/assets/images/background_regle.jpg
  src/Controller/GameController.php
  src/View/Game/rules.html.twig
  src/View/Game/troop.html.twig
Labels: Corrections done

#28 US-20_menu
  public/assets/css/style.css
  public/assets/images/wall.png
  simple-mvc.sql
  src/Controller/ItemController.php
  src/Model/ItemManager.php
  src/View/Game/troop.html.twig
  src/View/Home/index.html.twig
  src/View/Item/_form.html.twig
  src/View/Item/add.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#35 Us 05 08 09 repos entraînement fatigue
  src/Controller/GameController.php
  src/Model/Troop.php
  src/Model/TroopManager.php
  src/View/Game/troop.html.twig
Labels: Reviewed

#29 Ajout d'une page legal notice
  public/assets/css/legal.css
  public/assets/images/background_legal.jpg
  src/View/Game/legal.html.twig
Labels: Reviewed

#36 US-11_customization
  public/assets/css/bg-barad-dur.css
  public/assets/css/bg-castle-upload.css
  public/assets/css/bg-castlevania.css
  public/assets/css/bg-defend-the-castle.css
  public/assets/css/bg-error.css
  public/assets/css/bg-winterfell.css
  public/assets/css/style.css
  public/assets/images/bg-barad-dur.jpg
  public/assets/images/bg-castlevania.jpg
  public/assets/images/bg-defend-the-castle.png
  public/assets/images/bg-error.png
  public/assets/images/bg-winterfell.jpg
  public/upload/bg-castle-upload.png
  src/Controller/GameController.php
  src/Model/Castle.php
  src/Model/CastleManager.php
  src/View/Game/troop.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#37 Ajout animations de la carte attacker et changement du background page legal
  public/assets/css/legal.css
  public/assets/css/rules.css
  public/assets/css/style.css
  public/assets/images/wood.jpg
  src/Controller/GameController.php
  src/View/Game/legal.html.twig
  src/View/Game/rules.html.twig
Labels: Reviewed

#38 Faq
  public/assets/css/faq.css
  public/assets/font/1529 Champ Fleury W01 Regular.ttf
  public/assets/images/404.png
  public/assets/images/Chateau.jpg
  public/assets/images/icon.png
  src/Controller/GameController.php
  src/View/Game/faq.html.twig
Labels: Reviewed

#40 Ajout page 404
  public/assets/css/bg-error-404.css
  src/Controller/GameController.php
  src/View/Error/404.html.twig
  src/View/Game/rules.html.twig
  src/routing.php
Labels: Corrections done, Reviewed
